test-str.c: fix gcc warnings with FORTIFY_SOURCE enabled
* test_strncpy(). The test intentionally copies less than the total length
  of the string, so it looks like there is nothing we can do about it in
  the test other than explicitly ignoring the warnings.

    inlined from ‘test_strncpy’ at test-str.c:943:2:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’
      output may be truncated copying 1 byte from a string of length 8191 [-Werror=stringop-truncation]
      106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...

* test_strcat(). The fix for the warning below is to avoid using overlapping
  buffers in src and dst. This is actually a requirement for both strcat() and
  strncpy(), so fix both functions.

    inlined from ‘test_strcat’ at test-str.c:1052:2:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:128:10: error: ‘__builtin___strcat_chk’
      accessing 4097 or more bytes at offsets 4096 and 0 may overlap 1 byte at offset 4096 [-Werror=restrict]
      128 |   return __builtin___strcat_chk (__dest, __src, __bos (__dest));
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...

Signed-off-by: Alexey Kodanev <aleksei.kodanev@bell-sw.com>