aarch64: work around compiler weirdness...
For reasons unknown, once we have the openssl 3.5 patch series in place, we
somehow hit libgcc's test for certain hardware atomics on aarch64.

libgcc only implements this on aarch64, and it does it like:

  _Bool __aarch64_have_lse_atomics
    __attribute__((visibility("hidden"), nocommon));

  ...

  unsigned long int __getauxval (unsigned long int);

  /* Use a higher priority to ensure it runs before user constructors
     and library constructors with priority 100. */
  static void __attribute__((constructor (90)))
  init_have_lse_atomics (void)
  {
    unsigned long hwcap = __getauxval (AT_HWCAP);
    __aarch64_have_lse_atomics = (hwcap & HWCAP_ATOMICS) != 0;
  }

And so we get it linked in to the elf constructors, which for some
reason newer gnu-efi decided was a pretty good idea to implement.  As a
result we see:

  ld -o shimaa64.so --hash-style=sysv -nostdlib -znocombreloc -T /work/src/elf_aarch64_efi.lds -shared -Bsymbolic -L/work/src/gnu-efi/aarch64/lib -L/work/src/gnu-efi/aarch64/gnuefi -LCryptlib -LCryptlib/OpenSSL /work/src/gnu-efi/aarch64/gnuefi/crt0-efi-aarch64.o --build-id=sha1  --no-undefined shim.o globals.o memattrs.o mok.o netboot.o cert.o dp.o loader-proto.o tpm.o version.o errlog.o sbat.o sbat_data.o sbat_var.o pe.o pe-relocate.o httpboot.o csv.o load-options.o utils.o verify.o Cryptlib/libcryptlib.a Cryptlib/OpenSSL/libopenssl.a lib/lib.a /work/src/gnu-efi/aarch64/lib/libefi.a /work/src/gnu-efi/aarch64/gnuefi/libgnuefi.a -lefi -lgnuefi --start-group Cryptlib/libcryptlib.a Cryptlib/OpenSSL/libopenssl.a --end-group /usr/lib/gcc/aarch64-redhat-linux/16/libgcc.a lib/lib.a
  /usr/bin/ld.bfd: /usr/lib/gcc/aarch64-redhat-linux/16/libgcc.a(lse-init.o): in function `init_have_lse_atomics':
  (.text.startup+0x10): undefined reference to `__getauxval'
  make: *** [/work/src/Makefile:157: shimaa64.so] Error 1

Again, it's not clear to me why we're not hitting this before the
openssl 3.5 patch series; it looks to me like we should have started
seeing it as soon as we switched back to upstream gnu-efi.

In any event, if we _didn't_ have CTORS, this wouldn't get linked,
__aarch64_have_lse_atomics would be in .bss and it'd be 0, and none of
the libgcc code would believe we have these optional atomics in the
hardware.  Everything would work just fine.

This patch implements __getauxval() that returns 0 in all cases on
aarch64.

Signed-off-by: Peter Jones <pjones@redhat.com>