Fix include order
scan-build helpfully notes:

| In file included from shim.c:14:
| In file included from /home/pjones/devel/github.com/shim/sbat-aarch64/shim.h:183:
| /home/pjones/devel/github.com/shim/sbat-aarch64/include/hexdump.h:123:2: error: 'va_start' used in Win64 ABI function
|         va_start(ap, at);
|         ^
| /usr/lib/gcc/x86_64-redhat-linux/10/include/stdarg.h:47:23: note: expanded from macro 'va_start'
| #define va_start(v,l)   __builtin_va_start(v,l)
|                         ^

This is because one of the patches for the builtin swizzling is missing
a correction for the include order.  This patch fixes that order.

Signed-off-by: Peter Jones <pjones@redhat.com>